# Generated by Django 6.1.1 on 2026-10-07 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='версия'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='номер')),
                ('tree', models.JSONField(verbose_name='дерево')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.project')),
            ],
            options={
                'verbose_name': 'версия документа',
                'verbose_name_plural': 'версии документа',
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('project', 'number'), name='unique_document_version_per_project')],
            },
        ),
    ]
