# Generated by Django 6.1.1 on 2026-10-06 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('key', models.CharField(max_length=60, verbose_name='ключ')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='описание')),
                ('fields', models.JSONField(default=list, verbose_name='поля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='projects.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='внешний ключ')),
                ('data', models.JSONField(default=dict, verbose_name='значения')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='data_sources.datasource')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='unique_source_key_per_project'),
        ),
        migrations.AddConstraint(
            model_name='datarecord',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('source', 'external_id'), name='unique_external_id_per_source'),
        ),
    ]
