# Generated by Django 6.1.1 on 2026-10-07 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('section', 'Секция'), ('text', 'Текст'), ('media', 'Медиа')], max_length=16, verbose_name='компонент')),
                ('tokens', models.JSONField(default=dict, verbose_name='токены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_styles', to='projects.project')),
            ],
            options={
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('project', 'kind'), name='unique_component_style_per_project')],
            },
        ),
    ]
